### ISSUE TITLE
Latest GWEN (3.31.4) is failing when we pass newline character in data table

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#96]
**Steps to reproduce -**
1. Create feature file with below content and run it
```
Feature: TEST

@DataTable(header="top")
@StepDef
@ForEach
Scenario: Data table test
And value is defined by javascript "'${data[value]}'"

@StepDef
Scenario: Normal scenario test with "<value>" value
And value is defined by javascript "'$<value>'"

Scenario: Test
And Normal scenario test with "value with \n character" value
And Data table test
| value                   |
| value with \n character |
```
2. GWEN 3.31.4 is not able to handle newline character in data table
3. Same feature works fine with GWEN 3.2.0

**Env -**
GWEN version - 3.31.4
Chrome driver - Latest

![newline-charcter-issue](https://user-images.githubusercontent.com/86771461/193038019-0ec54d40-ae9e-4738-b67e-ee59e0e7bdfb.png)

**Comment by bjuric** [comment]
The problem was that the latest Gherkin parser no longer escapes new line characters from table cells. It expects \\n instead of \n. Solution was to escape any new line characters after parsing. Will be available in next release.

**Comment by bjuric** [comment]
Fix released in gwen-web [v3.31.6](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.31.6). Please close when ready.

**Comment by sse2ebdd** [comment]
Tested on GWEN 3.31.6, still failing when we pass `\n` in data table.
@bjuric Do we need to replace `\n` with `\\n` in data tables ?

**Comment by bjuric** [comment]
It was a windows issue. Implemented a platform independent solution. Fix released in gwen-web [v3.31.7](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.31.7).

**Comment by sse2ebdd** [comment]
@bjuric Data table scenario is now working as expected.
But similar issue observed when you have newline character in javascript.
```
Feature: TEST

Scenario: TEST
And value1 is defined by javascript "'a\nb'"
And value2 is "${value1}"
```

![newline-charcter-javascript-issue](https://user-images.githubusercontent.com/86771461/193212838-6317173b-46de-4b63-abd8-1a414331386c.png)

**Comment by bjuric** [comment]
Fix released in gwen-web [v3.31.8](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.31.8)

**Comment by bjuric** [comment]
OK the problem here now is that after `'a\nb` is evaluated by javascript it becomes: 
```
a
b
```

So the solution here is to put the `value2` assignment in a doc string:

```
Feature: TEST

Scenario: TEST
And value1 is defined by javascript "'a\nb'"
And value2 is
    """
    ${value1}
    """
```

Note that if however you defined `value1` as a literal value instead of a java script value as below, you would not need to use a doc string since `value1` would not be evaluated. Example:

```
And value1 is "'a\nb'"
And value2 is "${value1}"
```

**Comment by sse2ebdd** [comment]
Suggested solution is working as expected.
Hence closing this issue.
